services:
  ruby:
    build:
      context: .
    environment:
      - SECRET_KEY_BASE=abc
      - SW_HOSTNAME
    ports:
      - 3500:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/src
  sync:
    image: ghcr.io/skiller-whale/learnersync:0.2.1
    environment:
      SERVER_URL: https://train.skillerwhale.com/
      SW_RUNNING_IN_HOSTED_ENV:
      WATCHER_BASE_PATH: /src
      ATTENDANCE_ID_FILE: /sync/attendance_id
      WATCHED_EXTS: .rb .json .js .erb
      IGNORE_DIRS: .git tmp log storage
    volumes:
      - .:/src
      - ./attendance_id:/sync/attendance_id
